### ISSUE TITLE
cleanup code and remove unused functions

### ISSUE THREAD

**Issue by mzeevi** [dana-team/hns#16]
There is some left-over code from different iterations of the project that can be completely removed.

/good-first-issue
/kind cleanup

**Comment by maxfilov** [comment]
Good day, I would like to handle this one, but it's not clear what I can consider to be a `left-over`. Can I just delete all unused functions, constants and variables?

**Comment by mzeevi** [comment]
Hello!

Yes, should be simple enough. 

There's just a bunch of code all throughout that is either in comment or methods that are just completely unused. This is "left-over" from previous iterations of the code, which wasn't open-source until very recently, but they were not cleaned-up properly.

Note that `make test` currently doesn't run well, but we have issues to fix that as well: #8, #9, #10, #11, #12, so don't remove test stuff in this PR.

/assign @maxfilov

**Comment by maxfilov** [comment]
before I proceed with actual feature, I want to reformat code, this way reviewer will be able to understand the reason for changes. If I start removing code and then run `fmt`, there is a lot of code affected, not just the code for the issue.

@mzeevi https://github.com/dana-team/hns/pull/17
